name = input('이름을 입력하세요...: ')
print('안녕', name)
print('The length of your name is', len(name))
print('당신 이름은', str(len(name)) + '자 입니다.')
print('\n')
age = input('몇 살이세요? ')
print('You will be', str(int(age)+1), 'years old in the next year.')
print('내년에', str(int(age)+1) + '살이 되시는군요.')
print('Bye~~~!')
